#include <stdlib.h>
#include <errno.h>
#include <arpa/inet.h>
#include <string.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <stdio.h>
#include <pthread.h>
#include <dirent.h>
#include <netdb.h>
#include <libgen.h>
#include <signal.h>
#include <time.h>
#include <sys/stat.h>
#include "aes.c"
